profiles:
  web:
    title: 'Web'
    url: 'https://grails-profiles.github.io/web/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  restapi:
    title: 'Rest API'
    url: 'https://grails-profiles.github.io/rest-api/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  angularjs:
    title: 'AngularJS'
    url: 'https://grails-profiles.github.io/angularjs/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  angular:
    title: 'Angular'
    url: 'https://grails-profiles.github.io/angular/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  react:
    title: 'React'
    url: 'https://grails-profiles.github.io/react/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  reactwebpack:
    title: 'React-Webpack'
    url: 'https://grails-profiles.github.io/react-webpack/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  webpack:
    title: 'Webpack'
    url: 'https://grails-profiles.github.io/webpack/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  vue:
    title: 'Vue'
    url: 'https://grails-profiles.github.io/vue/latest/guide/index.html'
    category: 'Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Profiles encapsulate the project commands, templates, and plugins that are designed to work with a given profile. The source for the profiles can be found on [GitHub](https://github.com/grails-profiles/), while the profiles themselves are published as JAR files in the Grails central repository.'
  plugin:
    title: 'Plugin'
    url: 'https://grails-profiles.github.io/plugin/latest/guide/index.html'
    category: 'Plugin Profiles'
    image: '[%url]/images/profiles.svg'
  restplugin:
    title: 'REST API Plugin'
    url: 'https://grails-profiles.github.io/rest-api-plugin/latest/guide/index.html'
    category: 'Plugin Profiles'
    image: '[%url]/images/profiles.svg'
  webplugin:
    title: 'Web Plugin'
    url: 'https://grails-profiles.github.io/web-plugin/latest/guide/index.html'
    category: 'Plugin Profiles'
    image: '[%url]/images/profiles.svg'
  vaadin:
    title: 'Vaadin'
    url: 'https://github.com/macprzepiora/web-vaadin8'
    category: 'Third-Party Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Use the following documentation to learn how to [create your own application profiles](https://grails.apache.org/docs/latest/guide/profiles.html#creatingProfiles)'
  ember:
    title: 'Ember'
    url: 'https://github.com/hgarfer/grails-profile-ember'
    category: 'Third-Party Profiles'
    image: '[%url]/images/profiles.svg'
    description: 'Use the following documentation to learn how to [create your own application profiles](https://grails.apache.org/docs/latest/guide/profiles.html#creatingProfiles)'
