/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package website.gradle.tasks

import groovy.json.JsonOutput
import groovy.transform.CompileDynamic
import groovy.transform.CompileStatic
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.TaskProvider
import org.yaml.snakeyaml.Yaml

import website.gradle.GrailsWebsiteExtension

import java.time.Instant

/**
 * Generates a machine-readable redirect manifest published at
 * {@code https://grails.apache.org/guides/_redirects.json}. The manifest
 * mirrors the (legacy URL -> canonical URL) mapping deployed as meta-refresh
 * stubs by {@link GenerateRedirectStubsTask}, and is referenced from the
 * tombstone JSON on the legacy {@code guides.grails.org} gh-pages branch so
 * machine consumers can discover the redirect topology programmatically.
 *
 * The HTML stubs and the JSON manifest are intentionally generated by
 * separate tasks: the stubs ship to the legacy gh-pages branch (out-of-band
 * push), the manifest ships with the main site deploy
 * ({@code build/dist/guides/_redirects.json}).
 */
@CompileStatic
abstract class GenerateRedirectsManifestTask extends DefaultTask {

    static final String NAME = 'generateRedirectsManifest'
    static final String GROUP = 'migration'
    static final String LEGACY_BASE = 'https://guides.grails.org'
    static final String NEW_BASE = 'https://grails.apache.org/guides'

    @InputFile
    @PathSensitive(PathSensitivity.RELATIVE)
    abstract RegularFileProperty getGuidesYml()

    @InputFile
    @PathSensitive(PathSensitivity.RELATIVE)
    @Optional
    abstract RegularFileProperty getLegacyPaths()

    @OutputFile
    abstract RegularFileProperty getManifestFile()

    @TaskAction
    @CompileDynamic
    void generate() {
        File yml = guidesYml.get().asFile
        File outFile = manifestFile.get().asFile
        outFile.parentFile.mkdirs()

        Map root = yml.withReader('UTF-8') { new Yaml().load(it) as Map }
        List guides = root.guides as List ?: []

        // Build a name -> latest-version map mirroring GenerateRedirectStubsTask.
        Map<String, String> latestByName = [:]
        for (Map g : guides as List<Map>) {
            String name = g.name as String
            Map versions = g.versions as Map ?: [:]
            if (name && !versions.isEmpty()) {
                latestByName[name] = (versions.keySet() as List).sort().last() as String
            }
        }

        // (relPath -> targetUrl). Insertion order preserved for stable diffs.
        Map<String, String> map = new LinkedHashMap<>()

        // Per-guide canonical entry points + per-version legacy URL prefixes.
        for (Map g : guides as List<Map>) {
            String name = g.name as String
            Map versions = g.versions as Map ?: [:]
            if (!name || versions.isEmpty()) continue
            String latest = latestByName[name]
            String latestUrl = "${NEW_BASE}/${name}/${latest}/guide/index.html".toString()

            map["/${name}/guide/index.html".toString()]  = latestUrl
            map["/${name}/guide/single.html".toString()] = latestUrl
            map["/${name}/index.html".toString()]        = latestUrl

            for (Object versionKeyObj : versions.keySet()) {
                String v = versionKeyObj as String
                String slugAlt = (g.githubSlug as String)?.replace('grails-guides/', '')
                String versionedUrl = "${NEW_BASE}/${name}/${v}/guide/index.html".toString()
                for (String slug : [name, slugAlt].findAll { it }) {
                    map["/grails${v}/${slug}/guide/index.html".toString()] = versionedUrl
                }
            }
        }

        // Walk the captured legacy URL list for tag/category/chapter pages
        // that the per-guide loop did not cover.
        if (legacyPaths.isPresent()) {
            File legacy = legacyPaths.get().asFile
            if (legacy.isFile()) {
                legacy.eachLine('UTF-8') { String raw ->
                    String path = raw?.trim()
                    if (!path || !path.endsWith('.html')) return
                    String relWithSlash = '/' + path
                    if (map.containsKey(relWithSlash)) return
                    String target = GenerateRedirectsManifestTask.mapLegacyPath(path, latestByName)
                    if (target) {
                        map[relWithSlash] = target
                    }
                }
            }
        }

        // Site-wide entry points.
        map['/index.html'.toString()] = "${NEW_BASE}/index.html".toString()
        map['/404.html'.toString()]   = "${NEW_BASE}/index.html".toString()

        List<Map<String, String>> redirects = map.collect { String from, String to ->
            [from: from, to: to]
        }

        Map manifest = [
                version    : 1,
                generated  : Instant.now().toString(),
                from_base  : LEGACY_BASE,
                to_base    : NEW_BASE,
                count      : redirects.size(),
                description: 'Mapping of legacy guides.grails.org URLs to current canonical URLs on grails.apache.org/guides. Each from path is relative to from_base; each to URL is absolute. Mirrors the meta-refresh stubs deployed to grails-guides/grails-guides-template gh-pages.',
                redirects  : redirects,
        ]

        outFile.setText(JsonOutput.prettyPrint(JsonOutput.toJson(manifest)), 'UTF-8')
        logger.lifecycle("Wrote ${redirects.size()} redirect entries to ${outFile}.")
    }

    @CompileStatic
    private static String mapLegacyPath(String path, Map<String, String> latestByName) {
        if (path.startsWith('tags/')) {
            return "${NEW_BASE}/${path}".toString()
        }
        if (path.startsWith('categories/')) {
            return "${NEW_BASE}/${path}".toString()
        }
        // Per-guide chapter pages: /<guide>/<chapter>.html or
        // /<guide>/guide/pages/<chapter>.html map to the single-page rendering.
        String[] parts = path.split('/')
        if (parts.length >= 1) {
            String guideName = parts[0]
            String latest = latestByName[guideName]
            if (latest) {
                return "${NEW_BASE}/${guideName}/${latest}/guide/index.html".toString()
            }
        }
        return null
    }

    static TaskProvider<GenerateRedirectsManifestTask> register(
            Project project,
            GrailsWebsiteExtension siteExt
    ) {
        project.tasks.register(NAME, GenerateRedirectsManifestTask) { task ->
            task.group = GROUP
            task.description =
                    'Generates _redirects.json under build/dist/guides/ - the machine-readable mirror of the meta-refresh redirect stubs deployed to the legacy gh-pages branch.'
            task.guidesYml.set(project.rootProject.layout.projectDirectory.file('conf/guides.yml'))
            task.legacyPaths.set(project.rootProject.layout.projectDirectory.file('conf/legacy-guide-paths.txt'))
            task.manifestFile.set(siteExt.outputDir.file('dist/guides/_redirects.json'))
        }
    }
}
