name: Publish
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    if: github.repository == 'apache/grails-static-website'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      - name: "🔨 Build Website"
        env:
          GRAILS_WS_URL: https://grails.apache.org
        run: >
          ./gradlew clean build
      - name: "🚀 Publish Main Site"
        uses: apache/grails-github-actions/deploy-github-pages@asf
        env:
          GH_TOKEN: ${{ secrets.GRAILS_GHTOKEN }}
          GRADLE_PUBLISH_RELEASE: 'false'
          SOURCE_FOLDER: build/dist
          TARGET_REPOSITORY: 'apache/grails-website'
          DOCUMENTATION_BRANCH: 'asf-site-production'
      # TODO Fix Grails Guide Publishing    
      # - name: Publish Guides Site
      #   run: ./publish.sh
      #   env:
      #     GITHUB_SLUG: grails-guides/grails-guides-template
      #     GH_BRANCH: gh-pages
      #     GH_TOKEN: ${{ secrets.GRAILS_GHTOKEN }}
      #     GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
      #     GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
      #     GRADLE_TASK: buildGuide
