name: Publish
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    if: github.repository == 'apache/grails-static-website'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      - name: Publish Main Site
        run: ./publish.sh
        env:
          GITHUB_SLUG: apache/grails-static-website
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_BRANCH: asf-site-staging
          # AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          # AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
          GRADLE_TASK: build
          GRAILS_WS_URL: https://grails.staged.apache.org
      - name: Publish Guides Site
        run: ./publish.sh
        env:
          GITHUB_SLUG: grails-guides/grails-guides-template
          GH_BRANCH: gh-pages
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
          GRADLE_TASK: buildGuide
